"""Added platform column to cryptocurrency table

Revision ID: 58bdd630f00b
Revises: a2a6e116c78c
Create Date: 2025-04-10 18:56:24.760727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58bdd630f00b'
down_revision: Union[str, None] = 'a2a6e116c78c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cryptocurrency', sa.Column('platform', sa.String(), nullable=True))
    op.create_index(op.f('ix_cryptocurrency_platform'), 'cryptocurrency', ['platform'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cryptocurrency_platform'), table_name='cryptocurrency')
    op.drop_column('cryptocurrency', 'platform')
    # ### end Alembic commands ###
