"""Added cryptocurrency table

Revision ID: a2a6e116c78c
Revises: 
Create Date: 2025-04-09 16:35:26.387968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2a6e116c78c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cryptocurrency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cryptocurrency_id'), 'cryptocurrency', ['id'], unique=False)
    op.create_index(op.f('ix_cryptocurrency_symbol'), 'cryptocurrency', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cryptocurrency_symbol'), table_name='cryptocurrency')
    op.drop_index(op.f('ix_cryptocurrency_id'), table_name='cryptocurrency')
    op.drop_table('cryptocurrency')
    # ### end Alembic commands ###
