"""Added unique constraint to symbol and platform

Revision ID: de672c12479e
Revises: e19f60dbe312
Create Date: 2025-04-11 12:55:00.724247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de672c12479e'
down_revision: Union[str, None] = 'e19f60dbe312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cryptocurrency_symbol', table_name='cryptocurrency')
    op.create_index(op.f('ix_cryptocurrency_symbol'), 'cryptocurrency', ['symbol'], unique=False)
    op.create_unique_constraint('uq_symbol_platform', 'cryptocurrency', ['symbol', 'platform'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_symbol_platform', 'cryptocurrency', type_='unique')
    op.drop_index(op.f('ix_cryptocurrency_symbol'), table_name='cryptocurrency')
    op.create_index('ix_cryptocurrency_symbol', 'cryptocurrency', ['symbol'], unique=True)
    # ### end Alembic commands ###
