"""symbol and platform of cryptocurrency table set required

Revision ID: e19f60dbe312
Revises: 58bdd630f00b
Create Date: 2025-04-10 19:01:37.569333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e19f60dbe312'
down_revision: Union[str, None] = '58bdd630f00b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cryptocurrency', 'symbol',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cryptocurrency', 'platform',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cryptocurrency', 'platform',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cryptocurrency', 'symbol',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
